In [64]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [68]:
# Creating a Numpy Array

lst = [1,2,3,4]
arr = np.array(lst)
print(arr)

[1 2 3 4]


In [75]:
# .dtype attribute
print(arr.dtype)

int32


In [79]:
"""
Size Comparison of ndarray and list objects
"""
from sys import getsizeof

lst = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
print(getsizeof(lst)) # 56 -> 64 int + object meta info

arr = np.array(lst)
print(getsizeof(arr)) # 96 -> 100 .int(4bytes)

176
160


In [81]:
prices = [30,25,40,20,35,50,35]
new_prices = [price - 5 for price in prices]
print(new_prices)

prices_arr = np.array(prices)
prices_arr -= 5
print(prices_arr)

[25, 20, 35, 15, 30, 45, 30]
[25 20 35 15 30 45 30]


In [51]:
# exercise: Operation With Test Scores

In [52]:
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

In [53]:
test_3_fixed = test_3 + 2

In [43]:
total_grade = test_1 + test_2 + test_3_fixed

In [129]:
final_grade = np.trunc(total_grade / 3).astype('int')

In [122]:
jeremy_test_2 = np.array(test_2[3])
Manual_Adwoa_test_1 = np.array([test_1[1],test_1[2]])

In [127]:
student_scores = np.array([test_1,test_2,test_3])
# student_scores = np.concatenate([[test_1,test_2,test_3]],axis = 0)
print(student_scores)

[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]


In [132]:
Tanya_test_3 = student_scores[-1,0]

In [125]:
Cody_test = student_scores[:,-1]

In [141]:
"""
Logical Operations With Arrays
 - 배열 원소 단위의 논리 연산
     - 원소 별로 논리식에 대한 bool 값을 계산
"""
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
mask = a > 5
print(mask)

# select usin Logival operations
selected = a[a > 5]

# combined Logical operations
selected = a[(a > 6) | (a < 4)]
print(selected)

selected = a[(a > 4) & (a < 8)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  2  2  3  9  8  9  7]
[5 7]


In [82]:
# exercise: Goldilocks Porridge Festival

In [84]:
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

In [88]:
cold = porridge[porridge < 60]

In [90]:
hot = porridge[porridge > 80]

In [135]:
just_right = porridge[(porridge >= 60) & (porridge <= 80)]
print(just_right)

[79 65 63 79]
