- numpy 배열 조작 유형
1. 배열 속성 지정: 배열의 크기, 형상(shape / dimension), 메모리 소비량, 데이터 타입을 결정
2. 배열 인덱싱: 배열의 개별 원소에 접근 및 값 할당
3. 배열 슬라이싱: 배열의 부분집합을 계산
4. 배열 재구조화: 배열의 형상을 변경
5. 배열 결합 및 분할

Creating an array

np.arange(start, stop, step) : 특정 범위의 정수 배열 생성

- start: 범위 시작 값(포함), 디폴트 값:0
- stop: 범위 마지막 값(제외)
- step: 간격, 디폴트 값: 1

난수(random number) 배열 생성하기
 - np.random.seed(num): 똑같은 난수 배열 생성을 위한 시드 값
 - np.random.randint(high, size): 정수로 구성된 난수 배열 생성

Numpy Array Attributes

Numpy 배열 속성
 - arr.ndim: 차원 개수(num of dimension)
 - arr.shape: 배열의 크기
 - arr.size: 전체 배열의 크기(배열 원소 개수)
 - arr.dtype: 배열 데이터 타입
 - arr.itemsize: 배열 원소 별 메모리 크기
 - arr.nbytes: 전체 배열 메모리 크기 (nbytes = itemsize * size)

Array Slicing: Accessing Subarrays

- 배열 슬라이싱: 배열의 부분집합을 선택
    - arr[start:stop:step]

Multi-dimensional Subarrays

- 다차원 배열 슬라이싱
    - Ex. 2차원배열: arr[start1:stop1:step1, start2:stop2:step2]

Subarrays as Views
 - 배열 슬라이스는 복사본(copy)이 아닌 뷰(view)
     - 배열 슬라이스 값을 변경 => 원본 배열 값도 변경됨(리스트와 다름)

Reshaping of Arrays

- 배열의 형상(shape) = 행렬(배열)의 차원(dimension)
    - 배열의 형상을 변경(재구조화)하여 처리하는 경우가 많음(Ex. 머신러닝/딥러닝)
- arr.reshape(): 배열 형상 변경 메서드
    - 변경 전/후의 배열 크기가 동일해야함.

Array Concatenation

- 배열 연결: 두개 이상의 배열을 하나로 결합
    - np.concatenate(): 배열 연결 메서드

- np.vstack(): 종(vertical) 방향으로 배열 연결
- np.hstack(): 횡(horizontal) 방향으로 배열 연결

Array Splitting

- 배열 분할: 배열을 두개 이상의 부분 배열로 나누기
    - np.split(),np.vsplit(), np.hsplit(): 배열 분할 메서드

- 재구조화의 흔한 패턴: 차원을 추가
    - Ex. 1차원 배열(row-vector) => 2차원 행렬(matrix)
- np.newaxis: 배열의 추가 차원

In [19]:
import numpy as np

In [20]:
# arange
a = np.arange(1,5,2)

In [21]:
# random
b = np.random.seed(0) # 이전과 같은 난수 배열을 얻기 위해 시드 설정

arr1 = np.random.randint(10, size = 6)
arr2 = np.random.randint(10, size = (3,4))
arr3 = np.random.randint(10, size = (3,4,5))

In [29]:
# Attributes
print("arr2.ndim = ", arr2.ndim)
print("arr2.shape = ", arr2.shape) # ***
print("arr2.size = ", arr2.size) # ***

print("arr2.dtype = ", arr2.dtype) # ***
print("arr2.itemsize = ", arr2.itemsize)
print("arr2.nbytes = ", arr2.nbytes)

arr2.ndim =  2
arr2.shape =  (3, 4)
arr2.size =  12
arr2.dtype =  int32
arr2.itemsize =  4
arr2.nbytes =  48


In [32]:
# Array Slicing: Accessing Subarrays

arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [38]:
# Multi-dimensional Subarrays
np.random.seed(0)
arr = np.random.randint(10, size = (6,8))

print(arr)
arr_sub = arr[3:5, 4:7]
print(arr_sub)
print(arr[:2,:3])

[[5 0 3 3 7 9 3 5]
 [2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7]]
[[5 0 2]
 [3 7 0]]
[[5 0 3]
 [2 4 7]]


In [44]:
"""
Subarrays as no-copy views
"""
np.random.seed(0)

arr = np.random.randint(10, size = (3,4))
print(arr, '\n')

arr_sub = arr[:2, :2] # -arr.copy(): 배열(또는 슬라이스) 복사본 생성
print(arr_sub, '\n')

arr_sub[0,0] = 99
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

[[5 0]
 [7 9]] 

[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


In [46]:
# .copy()

np.random.seed(0)

arr = np.random.randint(10, size = (3,4))
print(arr)

arr_sub = arr[:2,:2].copy()
arr_sub[0,0] = 99
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [52]:
# Reshaping of Arrays - append dimension / np.newaxis
arr = np.array([1,2,3])
print("arr.ndim = ", arr.ndim)
print("arr.shape = ", arr.shape)

arr_new = arr[np.newaxis, :]
print(arr_new)
arr_new = arr[:, np.newaxis]
print(arr_new)

arr.ndim =  1
arr.shape =  (3,)
[[1 2 3]]
[[1]
 [2]
 [3]]


In [67]:
# np.concatenate()

arr1 = np.array([[1,2,3],[1,2,3]])
arr2 = np.array([[4,5,6],[4,5,6]])
arr3 = np.array([[7,8,9],[7,8,9]])

arr_total = np.concatenate([arr1,arr2,arr3], axis = 1)
print(arr_total)

arr_total = np.vstack([arr1,arr2,arr3])
print(arr_total)

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]]


In [69]:
"""
np.split()
"""

arr = np.array([1,2,3,99,99,3,2,1])
arr1, arr2, arr3 = np.split(arr, [3,5])
print(arr1, arr2, arr3)

[1 2 3] [99 99] [3 2 1]
