Universal Funcitions (UFuncs)
 - 유니버셜 함수: Numpy에서 ㅈ공하는 벡터화 연산 함수 (numpy.ufunc)
     - 다차원 배열에 대한 원소 별 (element-wise) 연산을 수행
     - 벡터화(vectorization): 루프 연산을 인터프리터 계층이 아닌 컴파일 계층에서 수행
     > 배열 연산을 빠르게 처리
     - 유연한 연산 제공: 스칼라배열, 배열-배열, 다차원 배열 연산 등
         - 유니버설 함수의 벡터화 연산은 파이썬 루프로 구현된 연산보다 대부분 더 효율적
     - 파이썬 반복문을 작성할 때 벡터화 연산으로 대체 가능한지 검토할 필요가 있음.
     
     - 배열의 사칙연산: 파이썬 기본 산술 연산자 또는 UFunc 사용
     
UFuncs: Absolute Value
 - np.abs(): 절댓값 함수
     - 파이썬에서 abs() 기본으로 제공하지만, 벡터화 연산을 위해 np.abs()사용
     > cf. 복소수 절댓값 계산도 가능함.

UFuncs: linspace()

 - np.linspace(start, stop, num): 선형간격의 벡터 생성
     - 다양한 벡터/행렬 생성에 자주 사용됨
     
UFuncs: Trigonometric Functions
    
    - 삼각함수: 데이터과학에서 자주 사용되는 함수
        - np.sin(): 사인 함수
        - np.cos(): 코사인 함수
        - np.tan(): 탄젠트 함수
        - 역삼각함수: np.arcsin(), np.arccos(), np.arctan()
        
UFuncs: etc

    - 지수와 로그: np.exp(), np.power(), np.log(), np.log10() 등
    - 그외: 쌍곡선 삼각함수, 비트연산, 비교 연산자, 라디안 등
    - scipy.special: 고급 수치연산을 유니버설 함수 형태로 제공하는 패키지
        - 감마함수, 가우스 적분, 보수/역수 등
        
UFuncs: Aggregation

    - 데이터의 기술통계(descriptive statistics)를 위한 집계 함수 제공
    - reduce(): 배열을 특정 연산으로 축소
    - accumulate(): 계산의 중간 결과들을 배열로 저장
    - 배열 합계 계산: np.sum()
         > 파이썬 내장함수 sum()보다 연산이 훨씬 빠름

Multi Dimensional Aggregates
    
    - 다차원 집계: 특정 차원을 기준으로 집계
        - axis 속성
            > aixs = 0 : 세로
            > axis = 1 : 가로

In [21]:
import numpy as np
"""
Computing reciprocals in loops
"""
# Function for computing reciprocals using looping
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
values = np.random.randint(1,10, size = 5)
print(values)

[8 7 2 1 2]


In [22]:
"""
Comparison: Loop vs ufuncs(vectorized)
"""

big_array = np.random.randint(1,100, size = 1000000)

# Looping on a big array

# jupyter magic function (%timeit)
%timeit compute_reciprocals(big_array)

2.89 s ± 320 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [23]:
# Vectorized operations
%timeit 1 / big_array

5.63 ms ± 711 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [24]:
"""
numpy.ufunc
"""

np.random.seed(1)
arr1 = np.random.randint(10, size = 5)
arr2 = np.random.randint(10, size = 5)
print(arr1, arr2)
arr1 = arr2 - 2
print(arr1, arr2)

arr3 = arr1 + arr2
print(arr3)

arr4 = np.random.randint(10, size = (3,5))
print(arr4)

arr5 = arr4 ** 2
print(arr5)

[5 8 9 5 0] [0 1 7 6 9]
[-2 -1  5  4  7] [0 1 7 6 9]
[-2  0 12 10 16]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [26]:
"""
UFuncs: Absolute value
"""

x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [34]:
"""
UFuncs: Trigonometric Functions
"""

theta = np.linspace(0, np.pi, 3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

x = np.linspace(0, 100, 10, dtype = 'int32')
print(x)

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[  0  11  22  33  44  55  66  77  88 100]


In [36]:
"""
UFuncs: Aggregation
"""

x = np.arange(1, 5)
print(x)
aggr = np.add.reduce(x)
print(aggr)

aggr = np.multiply.reduce(x)
print(aggr)

[1 2 3 4]
10
24


In [39]:
# accumulate()
print(x)

accum = np.add.accumulate(x)
print(accum)

accum = np.multiply.accumulate(x)
print(accum)

[1 2 3 4]
[ 1  3  6 10]
[ 1  2  6 24]


In [42]:
# Summing the values in an Array

np.random.seed(3)
arr = np.random.rand(1000000) # rand(): creat 0 ~ 1 real numbers create

print(arr)
print('sum = ', np.sum(arr))

[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
sum =  500422.19897015305


In [43]:
%timeit sum(arr)

91 ms ± 4.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [45]:
%timeit np.sum(arr) # 1000µs = 1ms

1.67 ms ± 92.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [51]:
# Other Aggr. functions

print("max = ", np.max(arr))
print("min = ", np.min(arr))
print("median = ", np.mean(arr))
print("percentile = ", np.percentile(arr, 90))

print(np.any(arr > 1))
print(np.all(arr > 0)) # range(0, 1)

max =  0.9999996367889004
min =  1.5496004267534502e-06
median =  0.500422198970153
percentile =  0.9001765340710965
False
True


In [55]:
# Multi dimensional aggregates

np.random.seed(5)
arr = np.random.randint(10, size = (3,4))
print(arr)

print(np.sum(arr))
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
51
[12 14 17  8]
[15 28  8]
